name: ci

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - master
      - main
      - 'release-*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        golang: ['1.13', '1.16', '1.17']
        # currently, we cannot run non-x86_64 machines on Github Actions cloud env.
    runs-on: ${{ matrix.os }}-latest
    name: CI golang ${{ matrix.golang }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: ${{ matrix.golang }}
      - name: Change GO11MODULES
        run: go env -w GO111MODULE=auto
      - name: Install requirements
        run: |
          go get github.com/bmizerany/assert
          go get github.com/philhofer/fwd
          go get github.com/tinylib/msgp
      - name: Test
        run: go test -v ./fluent
